# Generated by Django 4.2.6 on 2024-02-01 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recommended_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='referral_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
