# Generated by Django 5.0.1 on 2024-02-03 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_profile_recommended_by_profile_referred_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referred_users',
            field=models.ManyToManyField(blank=True, related_name='referral_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
