# Generated by Django 5.0.1 on 2024-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_profile_parent_alter_profile_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
