# Generated by Django 5.0.1 on 2024-02-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
            ],
        ),
    ]
