# Generated by Django 5.2.6 on 2025-09-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_userprofile_recommended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='refferal_code',
            field=models.CharField(blank=True, default=1, max_length=12),
            preserve_default=False,
        ),
    ]
