# Generated by Django 5.2.6 on 2025-09-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_userprofile_refferal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
